### ISSUE TITLE
installed_distributions() gives an unhandled exception on Ubuntu 20.04 for distro-info

### ISSUE THREAD

**Issue by DavidRaymond** [di/pip-api#66]
If installed_distributions() finds any package that it thinks has an invalid version, it throws an unhandled exception and so can't be used to look at versions of any installed packages.
```$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pip_api
>>> pip_api.installed_distributions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/david/.local/lib/python3.8/site-packages/pip_api/_installed_distributions.py", line 85, in installed_distributions
    return _new_installed_distributions()
  File "/home/david/.local/lib/python3.8/site-packages/pip_api/_installed_distributions.py", line 77, in _new_installed_distributions
    ret[name] = Distribution(name, version, location)
  File "/home/david/.local/lib/python3.8/site-packages/pip_api/_installed_distributions.py", line 12, in __init__
    self.version = Version(version)
  File "/home/david/.local/lib/python3.8/site-packages/pip_api/_vendor/packaging/version.py", line 277, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
pip_api._vendor.packaging.version.InvalidVersion: Invalid version: '0.23ubuntu1'
>>> 
```
This was first found with other packages, but has been reproduced on a fresh build of Ubuntu20.04 with just python3-pip and pip_api installed.  In that test environment it fails with the distro-info package that was pre-installed in the system.

**Comment by di** [comment]
Thanks! Fixed in https://pypi.org/project/pip-api/0.0.19/

**Comment by DavidRaymond** [comment]
Thanks - an impressively quick fix.  Works fine for me now.
