### ISSUE TITLE
_call.py - environment variables are being override in the subprocess.check_output method

### ISSUE THREAD

**Issue by tomerk669** [di/pip-api#68]
Recently, as part of the change in commit  **'Always set PIP_YES to avoid prompts'** (a21d85) a dictionary was added as an env argument into the subprocess.check_output method. 

When setting the env argument, the called sub-process can't access the environment variable of the base process.

The impact is that i'm getting an error (attached below) when i try to import the last version of  pip-api (0.0.19) 

The following code change solved the problem on my host : 

![image](https://user-images.githubusercontent.com/15930676/108732944-b331c800-7536-11eb-88f6-3709d094fa08.png)

i would recommend to add the PIP_YES variable upon the existing system variable.  

### More Information

**Error message**:

![error message](https://user-images.githubusercontent.com/15930676/108729359-1a4d7d80-7533-11eb-8fc3-16e2e43f514f.png)

**Subprocess module note about env variable** :

![image](https://user-images.githubusercontent.com/15930676/108732808-91d0dc00-7536-11eb-893f-0bfec4202456.png)

**Comment by tomerk669** [comment]
I forgot to mention that i'm using [pip-download library ](https://github.com/youngquan/pip-download/blob/master/pipdownload/cli.py) - which actually call the pip-api import on line 12.

**Comment by di** [comment]
Thanks for raising! Looks like we should be merging `PIP_YES` into `os.environ` and passing that as `env` instead.

**Comment by KyleKing** [comment]
I also ran into this issue with `pip-download` and `isort`. In particular, `SYSTEMROOT` was being overridden on Windows, so I would see the error (`Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python`)

Locally, I added: `env = {**os.environ, **{"PIP_YES": "true"}}` which resolved the issues for me

Full traceback below (note: using `better-exceptions which prints intermediary variables)

```batch
C:\Users\king.kyle\Developer\project>python -m isort inst_scripting\cap_sense_analysis.py
Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python
Python runtime state: preinitialized

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
    |                          |                   |         -> <class 'runpy._Error'>
    |                          |                   -> 'isort'
    |                          -> <function _get_module_details at 0x00000108955DA1F0>
    -> 'isort'
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
           |                   |              -> <class 'runpy._Error'>
           |                   -> 'isort.__main__'
           -> <function _get_module_details at 0x00000108955DA1F0>
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
               -> 'isort'
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\isort\__init__.py", line 4, in <module>
    from .api import ImportKey
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\isort\api.py", line 10, in <module>
    from isort import core
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\isort\core.py", line 9, in <module>
    from . import output, parse
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\isort\output.py", line 8, in <module>
    from . import parse, sorting, wrap
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\isort\parse.py", line 10, in <module>
    from .deprecated.finders import FindersManager
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\isort\deprecated\finders.py", 
line 28, in <module>
    from pip_api import parse_requirements
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\pip_api\__init__.py", line 8, 
in <module>
    PIP_VERSION = packaging_version.parse(version())
                  |                       -> <function version at 0x0000010895828160>
                  -> <module 'pip_api._vendor.packaging.version' from 'C:\\Users\\king.kyle\\Developer\\Packages\\inst_scripting\\.venv\\lib\\site-pa...
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\pip_api\_version.py", line 5, 
in version
    result = call("--version")
             -> <function call at 0x00000108958281F0>
  File "C:\Users\king.kyle\Developer\project\.venv\lib\site-packages\pip_api\_call.py", line 11, in call
    result = subprocess.check_output(
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\Users\\king.kyle\\Developer\\Packages\\inst_scripting\\.venv\\Scripts\\python.exe', '-m', 'pip', '--version']' returned non-zero exit status 1.
```

**Comment by di** [comment]
I would be happy to merge a PR with that change, thanks!

**Comment by di** [comment]
Fixed in https://pypi.org/project/pip-api/0.0.20/

**Comment by KyleKing** [comment]
Tested on Windows 10; no issues!
